controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # FL Controllers
    FL_hip_controller:
      type: unitree_legged_control/UnitreeJointController
    FL_thigh_controller:
      type: unitree_legged_control/UnitreeJointController
    FL_calf_controller:
      type: unitree_legged_control/UnitreeJointController

    # FR Controllers
    FR_hip_controller:
      type: unitree_legged_control/UnitreeJointController
    FR_thigh_controller:
      type: unitree_legged_control/UnitreeJointController
    FR_calf_controller:
      type: unitree_legged_control/UnitreeJointController

    # RL Controllers
    RL_hip_controller:
      type: unitree_legged_control/UnitreeJointController
    RL_thigh_controller:
      type: unitree_legged_control/UnitreeJointController
    RL_calf_controller:
      type: unitree_legged_control/UnitreeJointController

    # RR Controllers
    RR_hip_controller:
      type: unitree_legged_control/UnitreeJointController
    RR_thigh_controller:
      type: unitree_legged_control/UnitreeJointController
    RR_calf_controller:
      type: unitree_legged_control/UnitreeJointController

# FL Controllers parameters
FL_hip_controller:
  ros__parameters:
    joint: FL_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

FL_thigh_controller:
  ros__parameters:
    joint: FL_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

FL_calf_controller:
  ros__parameters:
    joint: FL_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

# FR Controllers parameters
FR_hip_controller:
  ros__parameters:
    joint: FR_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

FR_thigh_controller:
  ros__parameters:
    joint: FR_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

FR_calf_controller:
  ros__parameters:
    joint: FR_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

# RL Controllers parameters
RL_hip_controller:
  ros__parameters:
    joint: RL_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

RL_thigh_controller:
  ros__parameters:
    joint: RL_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RL_calf_controller:
  ros__parameters:
    joint: RL_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

# RR Controllers parameters
RR_hip_controller:
  ros__parameters:
    joint: RR_hip_joint
    pid: {p: 100.0, i: 0.0, d: 5.0}

RR_thigh_controller:
  ros__parameters:
    joint: RR_thigh_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}

RR_calf_controller:
  ros__parameters:
    joint: RR_calf_joint
    pid: {p: 300.0, i: 0.0, d: 8.0}
